import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";

const popins = Poppins({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Webgenix",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html
				lang="en"
				className={`h-full antialiased ${popins.className}`}
			>
				<body className="min-h-full flex flex-col">
					<Provider>{children}</Provider>
					<Toaster position={"bottom-right"} />
				</body>
			</html>
		</ClerkProvider>
	);
}
